# Generated by Django 3.1.7 on 2021-04-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, unique=True, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门表',
                'verbose_name_plural': '部门表',
                'db_table': 'depart_info',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('salary', models.FloatField(verbose_name='工资')),
                ('age', models.CharField(max_length=255, verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '其他')], verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('head_pic', models.ImageField(null=True, upload_to='pic', verbose_name='头像')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '员工信息表',
                'verbose_name_plural': '员工信息表',
                'db_table': 'employee_info',
            },
        ),
    ]
