# Generated by Django 3.1.7 on 2021-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='head_pic',
            field=models.ImageField(default='pic/1G226143519-7.jpg', null=True, upload_to='pic', verbose_name='头像'),
        ),
    ]
