# Generated by Django 3.2 on 2021-04-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.SmallIntegerField(verbose_name='年龄'),
        ),
    ]
