# Generated by Django 3.1.7 on 2021-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210406_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='head_pic',
            field=models.ImageField(null=True, upload_to='pic', verbose_name='头像'),
        ),
    ]
