# Generated by Django 3.1.7 on 2021-04-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '其他')], default=0, verbose_name='性别'),
        ),
    ]
