# Generated by Django 3.1.7 on 2021-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210402_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '其他')], default=2, verbose_name='性别'),
        ),
    ]
